### ISSUE TITLE
Does ToMe work for focal modulation networks?

### ISSUE THREAD

**Issue by subneed** [facebookresearch/ToMe#24] opened 2023-03-21 06:24 UTC
any help on modifying ToMe for focal modulation networks?
I guess in FMN we could apply tome on Q/M. Also it has downsampling layers in each stage, so r value changes each stage and model definition?

**Comment by dbolya** [comment] 2023-03-21 16:30
Duplicate of #23

**Closed as completed by dbolya** 2023-03-21 16:30 UTC
